### PR TITLE
Ember frontend application with authentication

### PR DESCRIPTION
**Pull request by ioantsaf**
This pull request is the continuation of https://github.com/grnet/okeanos-LoD/pull/74

quoting @efikalti:
- User login components
- Ansible tasks for installing and configuring ember
- Ansible task for configuring apache server for CORs requests

Ansible looks for ember in the /var/www/okeanos-LoD/webapp/frontend path to change the files which should be downloaded from devel.Since that part is not merged into the devel branch the path does not exists and the tasks will fail.

To test the tasks before merging, add manually the folder frontend from this branch to the path /var/www/okeanos-LoD/webapp/ .

### CODE REVIEW

**Comment by pkoro** [comment]
@ioantsaf there are several empty files that are passed along with this PR (i.e. `.gitkeep` and others). Can you please remove them (unless of course they are needed)?

**Comment by grnetci** [comment]
Can one of the admins verify this patch?

**Comment by grnetci** [comment]
Can one of the admins verify this patch?

**Comment by themiszamani** [comment]
test this please

**Comment by ioantsaf** [comment]
please review @efikalti

**Comment by efikalti** [comment]
+1

**Pull request merged**
