### PR TITLE
Bug No6: Validate Kafka Topics

### PR DESCRIPTION
**Pull request by gouzouni625**
## Description

When the use enters the desired names for the Apache Kafka topics, validate these names so that:
1) The same name doesn't appear more that once in each group (input topics, output topics)
2) The same name doesn't appear both as an input and as an output topic.
## Changes

One can check the changes on the following Service-VM: snf-703866.vm.okeanos.grnet.gr

### CODE REVIEW

**Comment by gouzouni625** [comment]
Please review @ioantsaf @efikalti

**Comment by gouzouni625** [comment]
Please review @ioantsaf @efikalti

**Comment by gouzouni625** [comment]
Please review @ioantsaf @efikalti

**Comment by ioantsaf** [comment]
+1

**Pull request merged**
