### PR TITLE
LAM-155 Pre-register user on the database via Ansible

### PR DESCRIPTION
**Pull request by stevelaskaridis**
# Components
- Allow only one User record in database
- Pre-load owner of the service-vm inside its database from ansible during deployment

### CODE REVIEW

**Comment by themiszamani** [comment]
test this please

**Comment by themiszamani** [comment]
test this please

**Comment by stevelaskaridis** [comment]
It is marked as WIP. So that's what I am doing ...

**Comment by stevelaskaridis** [comment]
Please review @ioantsaf.

Remember to change the following to test:

``` diff
./webapp/ansible/roles/service-vm/vars/main.yml

-repository_url: https://github.com/grnet/okeanos-LoD.git
-repository_branch: devel
+repository_url: https://github.com/stevelaskaridis/okeanos-LoD.git
+repository_branch: LAM-155
```

**Comment by themiszamani** [comment]
test this please

**Comment by themiszamani** [comment]
test this please

**Comment by grnetci** [comment]
Can one of the admins verify this patch?

**Comment by themiszamani** [comment]
test this please

**Comment by themiszamani** [comment]
retest this please

**Comment by grnetci** [comment]
Can one of the admins verify this patch?

**Comment by ioantsaf** [comment]
+1

**Pull request merged**
