### PR TITLE
LAM-85 List Lambda Applications on Web UI

### PR DESCRIPTION
**Pull request by stevelaskaridis**
## Description

List lambda applications of the current user on the Web UI using Ember.js.
## Supported features
- List lambda applications.
- CSS integration.
- Pagination support.
- Linking to specific lambda instance on click.
- Live reload.
## To-dos
- Button actions functionality pending.
## Blocking issues
- Return **status** and **type** information from the API.

### CODE REVIEW

**Comment by stevelaskaridis** [comment]
Please review @gouzouni625 || @ioantsaf.

**Comment by themiszamani** [comment]
test this please

**Comment by grnetci** [comment]
Can one of the admins verify this patch?

**Comment by ioantsaf** [comment]
+1

**Pull request merged**
