### PR TITLE
LAM-176 test improvements for the fokia package

### PR DESCRIPTION
**Pull request by makistsantekidis**

### CODE REVIEW

**Comment by grnetci** [comment]
Can one of the admins verify this patch?

**Comment by themiszamani** [comment]
test this please

**Comment by themiszamani** [comment]
test this please

**Comment by themiszamani** [comment]
test this please

**Comment by makistsantekidis** [comment]
please review @gouzouni625 @ioantsaf

**Comment by pkoro** [comment]
+1

**Pull request merged**
