### PR TITLE
[LAM-130] Create and keep a new private/public key pair for each lambda instance creation

### PR DESCRIPTION
**Pull request by ioantsaf**
- [x] Each time a new lambda instance is created, the service VM creates a new key pair to ssh into the new cluster. The private key is kept into the /home/celery/.ssh/lambda_instances dir.
- [x] After the cluster creation, the ssh key file is added to the ssh config of the user celery, using the storm_ssh python lib. That way, the service VM (ansible) can communicate with all lambda instances.
- [x] After deleting a lambda instance, its keyfile is deleted from the service VM, along with its ssh config.
- [x] Move lambda_instance_destroy function from fokia.utils into fokia.lambda instance manager

### CODE REVIEW

**Comment by ioantsaf** [comment]
please review @pkoro @makistsantekidis

**Comment by gouzouni625** [comment]
I tried creating a few lambda instances and every time Ansible fails for some ssh related reason(2 times couldn't connect to master VM, 2 times couldn't connect to slave VMs).

Some logs gathered from the tasks worker:

```
[2015-09-09 06:33:49,776: WARNING/Worker-1] TASK: [wait_for_ssh | Wait for port 22 to be ready] ***************************
[2015-09-09 06:33:55,331: WARNING/Worker-1] ok: [snf-673731.vm.okeanos.grnet.gr -> 127.0.0.1] => {"changed": false, "elapsed": 5, "path": null, "port": 22, "search_regex": "OpenSSH", "state": "started"}
[2015-09-09 06:33:55,333: WARNING/Worker-1] PLAY [master] *****************************************************************
[2015-09-09 06:33:55,334: WARNING/Worker-1] GATHERING FACTS ***************************************************************
[2015-09-09 06:33:56,186: WARNING/Worker-1] fatal: [snf-673731.vm.okeanos.grnet.gr] => SSH Error: ssh_exchange_identification: Connection closed by remote host
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.

```

**Comment by ioantsaf** [comment]
I fixed the slave issue

**Comment by makistsantekidis** [comment]
+1 created new service-vm with ansible and created a new lambda instance successfully

**Pull request merged**
