### PR TITLE
Generic webapp adapter and serializer

### PR DESCRIPTION
**Pull request by ioantsaf**
This is the first implementation of generic webapp adapter and serializer.
The serializer serializes the responses from the lambda API. For specific API calls, one needs to extend the corresponding normalizeSingleResponse or normalizeArrayResponse methods of the application serializer, as in #115.

### CODE REVIEW

**Comment by ioantsaf** [comment]
please review @stevelaskaridis @gouzouni625

**Comment by gouzouni625** [comment]
Have you tried inheriting from these base classes? I think there might be a chance you need a name for them. Concretely, doing

```
export default DS.JSONAPISerializer.extend({ ...
```

doesn't give a name to the class you create, so, I think that you will not be able to inherit from it.

Doing

```
var SerializerName = DS.JSONAPISerializer.extend({ ... });

export default SerializerName;
```

would give a name to the class, so others could inherit from it by doing:

```
var CustomSerializer = SerializerName.extend({ ... });

export default CustomSerializer;
```

**Comment by gouzouni625** [comment]
Ok, scratch my previous comment. Seems like `export default` can be invoked only once in each JavaScript file, so one can inherit these classes by doing:

```
import GenericSerializer from "frontend/serializers/application";

export default CustomSerializer = GenericSerializer.extend({ ... });
```

**Comment by ioantsaf** [comment]
The name of the exported variables inside an ES6 module does not matter, as the variables are not published into the global namespace, but need to be imported. Indeed, I am extending my base serializer in #115 (https://github.com/ioantsaf/okeanos-LoD/blob/ember-details/webapp/frontend/app/serializers/lambda-instance.js), by importing the exported JSONAPISerializer class. Btw, in the application.js serializer, I am doing only one export (default), namely the JSONAPISerializer class, that contains all the overridden functions.

**Comment by gouzouni625** [comment]
+1

**Pull request merged**
