### PR TITLE
[LAM-173] Deploy an application

### PR DESCRIPTION
**Pull request by ioantsaf**
- [x] Deploy an application through the λ instances details view
- [x] Deploy an application through the λ instances list view
- [x] Deploy an application through the λ applications details view
- [x] Deploy an application through the λ applications list view
- [x] Improve the the λ instances list view attach button
- [x] Show type info in λ applications to-deploy list

### CODE REVIEW

**Comment by themiszamani** [comment]
test this please

**Comment by grnetci** [comment]
Can one of the admins verify this patch?

**Comment by ioantsaf** [comment]
please review @efikalti @stevelaskaridis

**Comment by efikalti** [comment]
+1

**Pull request merged**
