### PR TITLE
LAM-145 Statistics Logging to Central VM

### PR DESCRIPTION
**Pull request by gouzouni625**
# Description

Each Service VM should send statistical information to Central VM regarding the number on Lambda Instance and Applications running on it.
# To-Do
1. ~~Create Central VM Celery tasks~~
2. ~~Add calls to Central VM Celery tasks from Celery tasks~~
3. ~~Refactor tests for Celery tasks~~
4. ~~Add tests for Central VM Celery tasks~~
5. ~~Check that everything is working properly~~
6. ~~Update Central VM documentation~~

### CODE REVIEW

**Comment by gouzouni625** [comment]
Please review @stevelaskaridis .

**Comment by themiszamani** [comment]
test this please

**Comment by grnetci** [comment]
Can one of the admins verify this patch?

**Comment by themiszamani** [comment]
test this please

**Comment by gouzouni625** [comment]
test this

**Comment by stevelaskaridis** [comment]
GRNET CI is feeling under the weather.
+1 on the PR

**Pull request merged**
