### PR TITLE
LAM-183 Example Batch Job

### PR DESCRIPTION
**Pull request by gouzouni625**
# Description

Refactored example batch job to run with Apache Flink 0.9.1.
# To-Do

~~Add README.md file for the batch job~~

### CODE REVIEW

**Comment by themiszamani** [comment]
test this please

**Comment by grnetci** [comment]
Can one of the admins verify this patch?

**Comment by gouzouni625** [comment]
Please review.

**Comment by makistsantekidis** [comment]
+1

**Pull request merged**
