### PR TITLE
Web Pages for the Central VM

### PR DESCRIPTION
**Pull request by gouzouni625**
# Description

The Central VM is used for keeping statistics regarding ~okeanos Lambda on Demand Service. It is accessible by anyone without the need for any authentication.
# Information Served

The information that the user can see are:
1. Number of running Lambda Instances / Number of created Lambda Instances
2. Number of Subscribed Users
3. Number of uploaded Applications / Number of started Applications

### CODE REVIEW

**Comment by gouzouni625** [comment]
test this please

**Comment by gouzouni625** [comment]
Please review @pkoro .

**Comment by themiszamani** [comment]
test this please

**Comment by themiszamani** [comment]
test this please

**Comment by pkoro** [comment]
+1

**Pull request merged**
